### ISSUE TITLE
upload big file in low memory environment

### ISSUE THREAD

**Issue by lkthomas** [mohan3d/PyOpenload#16]
Traceback (most recent call last):
  File "upload_to_openload.py", line 11, in <module>
    uploaded_file_info = ol.upload_file(os.path.join(root, filename))
  File "/usr/local/lib/python2.7/dist-packages/openload/openload.py", line 258, in upload_file
    files={'upload_file': open(file_path, 'rb')}).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I am running it via Raspberry pi which is 1GB memory only, it looks like running out of memory when it uploads big files more than 1G, any idea how to fix it?

**Comment by mohan3d** [comment]
Hi @lkthomas ,

[Pyopenload](https://github.com/mohan3d/PyOpenload) depends on [requests](https://github.com/requests/requests) library which doesn't support these large files, 
but you can extend [Pyopenload](https://github.com/mohan3d/PyOpenload) to support your files. 

Start with this [example](https://pyopenload.readthedocs.io/en/latest/tutorial.html#upload-large-files) and let me know if you have problems.

**Comment by lkthomas** [comment]
the example you show is half broken, here is a code that I fixed,

import os
from openload import OpenLoad
from requests_toolbelt import MultipartEncoder
import requests

class MyOpenLoad(OpenLoad):
        def upload_large_file(self, file_path, **kwargs):
            response = self.upload_link(**kwargs)
            upload_url = response['url']

            _, file_name = os.path.split(file_path)

            with open(file_path, 'rb') as upload_file:
                data = MultipartEncoder({
                    "files": (file_name, upload_file, "application/octet-stream"),
                })

                headers = {"Prefer": "respond-async", "Content-Type": data.content_type}
                response_json = requests.post(upload_url, headers=headers, data=data).json()

            self._check_status(response_json)
            return response_json['result']

ol = MyOpenLoad('abc', 'abc')
uploaded_file_info = ol.upload_large_file('/foldert/test_large_file.mkv')

print(uploaded_file_info)

**Comment by mohan3d** [comment]
Thank you @lkthomas , I will update documentation example as soon as possible. 

Updated your code formatting.

If your problem solved please close this issue.

**Comment by lkthomas** [comment]
should we use large file upload method as default? May I ask why not put it as default?

**Comment by lkthomas** [comment]
@mohan3d , I still having some issue after switch to new code,

Traceback (most recent call last):
  File "./upload_to_openload.py", line 34, in <module>
    uploaded_file_info = ol.upload_large_file(os.path.join(root, filename))
  File "./upload_to_openload.py", line 20, in upload_large_file
    response_json = requests.post(upload_url, headers=headers, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by mohan3d** [comment]
> should we use large file upload method as default? May I ask why not put it as default?

For 3 reasons I didn't try to set large-files-upload as a default upload method.

- Due to the nature of streaming and how [requests-toolbelt](https://github.com/requests/toolbelt) work it might be slower than the ordinary upload.
- It's easy to extend [pyopenload](https://github.com/mohan3d/PyOpenload) as you did.
- Less dependencies.

**Comment by lkthomas** [comment]
I see, the last error could be caused by openload server under heavy load. I will reopen this ticket if I found anything unusual

**Comment by lkthomas** [comment]
Traceback (most recent call last):
  File "/SSD/BT/scripts/upload_to_openload.py", line 47, in <module>
    uploaded_file_info = ol.upload_large_file(os.path.join(root, filename))
  File "/SSD/BT/scripts/upload_to_openload.py", line 31, in upload_large_file
    response_json = requests.post(upload_url, headers=headers, data=data).json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 516, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 374, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 404, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

I still keep seeing this over the last 14 hours when I looping the upload and it keeps dying. 

is that possible for it to print debug log on JSON output?

**Comment by lkthomas** [comment]
found the problem isn't related with your code, because of unicode encoding problem on the file name, when I choose normal ascii file name to upload, everything is fine.
